export const B2B_CONFIG = {
  columns: [
    'region',
    'country',
    'sku_count',
    'title_tag_score',
    'description_tag_score',
    'h1_tag_score',
    'canonical_link_score',
    'feature_alt_score',
    'total_score_pct',
  ],
  labels: [
    'Region',
    'Country',
    'SKU',
    '1. Title\n(20)',
    '2. Description\n(20)',
    '3. H1\n(15)',
    '4. Canonical\n(15)',
    '5. Feature Alt\n(15)',
    'Total Score %',
  ],
  scoreColumns: [
    'title_tag_score',
    'description_tag_score',
    'h1_tag_score',
    'canonical_link_score',
    'feature_alt_score',
  ],
  scoreLabels: ['Title', 'Description', 'H1', 'Canonical', 'Feature Alt'],
  maxScores: [20, 20, 15, 15, 15],
  totalMax: 85,
};

export const B2C_CONFIG = {
  columns: [
    'region',
    'country',
    'division',
    'sku_count',
    'ufn_score',
    'basic_assets_score',
    'spec_summary_score',
    'faq_score',
    'title_score',
    'description_score',
    'h1_score',
    'canonical_score',
    'alt_feature_score',
    'alt_front_score',
    'total_score_pct',
  ],
  labels: [
    'Region',
    'Country',
    'Division',
    'SKU',
    'UFN\n(10)',
    'Basic\nAssets\n(10)',
    'Spec\nSummary\n(10)',
    'FAQ\n(10)',
    'Title\n(10)',
    'Description\n(10)',
    'H1\n(10)',
    'Canonical\n(10)',
    'Alt\nFeature\n(10)',
    'Alt\nFront\n(10)',
    'Total\nScore %',
  ],
  scoreColumns: [
    'ufn_score',
    'basic_assets_score',
    'spec_summary_score',
    'faq_score',
    'title_score',
    'description_score',
    'h1_score',
    'canonical_score',
    'alt_feature_score',
    'alt_front_score',
  ],
  scoreLabels: [
    'UFN',
    'Basic Assets',
    'Spec Summary',
    'FAQ',
    'Title',
    'Description',
    'H1',
    'Canonical',
    'Alt Feature',
    'Alt Front',
  ],
  maxScores: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
  totalMax: 100,
};

export const REGION_COLORS = {
  NA: '#2563eb',
  EU: '#16a34a',
  ASIA: '#ea580c',
  LATAM: '#8b5cf6',
  MEA: '#ec4899',
};
